## 数据操作

### 入门

In [71]:
import torch

In [72]:
# 创建向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
# 获取形状
x.shape

torch.Size([12])

In [74]:
# 元素总数
x.numel()

12

In [75]:
# 改变张量形状 
# x.reshape(-1, 4) 或 x.reshape(3, -1)
x = x.reshape(3, 4) 
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [76]:
# 全0
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [77]:
# 全1
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [78]:
# 随机
torch.randn(3, 4)

tensor([[-1.1261,  1.1221, -0.4947,  1.2055],
        [-0.7225, -0.2833,  0.5890,  0.8344],
        [ 0.1377,  0.3207, -0.3571,  1.0804]])

In [79]:
# 确定值
torch.tensor([[1, 2, 3, 4], [2, 5, 6, 3], [1, 5, 6, 4]])

tensor([[1, 2, 3, 4],
        [2, 5, 6, 3],
        [1, 5, 6, 4]])

### 运算符

In [80]:
# 加减乘除幂
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [81]:
# e的幂运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [82]:
# 沿行，按列连结两个张量
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [83]:
# 逻辑判断相等
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [84]:
# 所有元素求和
x.sum()

tensor(66.)

### 广播机制

In [85]:
# 通过复制元素扩展数组，以便两个张量转换成相同的形状
# 3 * 1 + 1 * 2 => 3 * 2
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

### 索引和切片

In [86]:
# 索引：从0开始，最后的一个元素为-1
# 1：3，指索引为1，2的元素
x[-1], x[1: 3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [87]:
# 指定索引写入元素
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [88]:
# 为多个元素赋相同的值
x[0: 2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 节省内存

In [89]:
# id为引用对象的确切地址
z = torch.zeros_like(y)
print('id(z):', id(z))
# 使用切片表示法节省内存 或 z += y
z[:] = x + y
print('id(z):', id(z))
# 操作为新结果分配内存
z = x + y
print('id(z):', id(z))

id(z): 2145327531024
id(z): 2145327531024
id(z): 2145327713648


### 转化为其他Python对象

In [90]:
# torch -> numpy
A = x.numpy()
# numpy -> torch
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [91]:
# 将大小为1的张量转化为Python标量
# 使用item()或Python内置函数如float()等
a = torch.tensor([3.5])
a, a.item(), int(a), float(a)

(tensor([3.5000]), 3.5, 3, 3.5)