## 线性代数

### 标量

In [2]:
import torch

# 加减乘除
x = torch.tensor(3.0)
y = torch.tensor(5.0)
x + y, x - y, x * y, x / y, x ** y

(tensor(8.), tensor(-2.), tensor(15.), tensor(0.6000), tensor(243.))

### 向量

In [3]:
x = torch.arange(4)
print(x)
# 通过索引访问任一元素
print(x[3])
# 长度
print(len(x))
# 形状
print(x.shape)

tensor([0, 1, 2, 3])
tensor(3)
4
torch.Size([4])


### 矩阵

In [34]:
# 通常用大写字母表示
A = torch.arange(20).reshape(5, 4)
# 转置
A, A.T, len(A)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]),
 5)

In [5]:
# 对称矩阵
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B, B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

### 张量

In [33]:
X = torch.arange(24).reshape(2, 3, 4)
# axis=0->两矩阵按元素位置各个相加
# axis=1->两矩阵分别按行求和
# axis=2->两矩阵分别按列求和
X, X.sum(axis=0), X.sum(axis=1), X.sum(axis=2), len(X)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]),
 2)

##### 张量计算

In [29]:
# 两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [8]:
# 矩阵按元素相乘

两个矩阵的按元素乘法称为Hadamard积（Hadamard product）。
$$
A \circ B =
\begin{vmatrix}
    a_{11}b_{11} & a_{12}b_{12} & ... & a_{1n}b_{1n} \\
    a_{21}b_{21} & a_{22}b_{22} & ... & a_{2n}b_{2n} \\
    ... & ... & ... & ... \\
    a_{n1}b_{n1} & a_{n2}b_{n2} & ... & a_{nn}b_{nn}
\end{vmatrix}
$$

In [9]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [10]:
# 标量与张量进行相加或相乘运算
# 张量的每个元素都将与标量相加或相乘
a = 2
a + A, a * A

(tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

### 降维

##### 降维求和

In [11]:
# 向量
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [12]:
# 矩阵
A, A.shape, A.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor(190.))

In [13]:
# 沿轴降维求和
# 按行求和, axis = 0
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [14]:
# 按列求和, axis = 1
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [15]:
# 行列求和
A.sum(axis=[0, 1])

tensor(190.)

##### 降维求平均值

In [16]:
# 平均值 = 总和 / 个数
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [17]:
# 对平均值函数沿轴降维
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

##### 非降维求和

In [18]:
# 保持轴数不变
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [19]:
# 广播
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [20]:
# 沿轴计算累计总和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

### 点积

In [21]:
# 相同位置的按元素乘积的和
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [22]:
# 相当于通过执行按元素乘法，然后进行求和
torch.sum(x * y)

tensor(6.)

### 矩阵-向量积

$$Ax = \begin{bmatrix}a^T_1\\a^T_2\\ \end{bmatrix} x = \begin{bmatrix}a^T_1 x\\a^T_2 x\\ \end{bmatrix}

In [23]:
A, x, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

### 矩阵-矩阵乘法

In [25]:
B = torch.ones(4, 3)
A, B, torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

### 范数

$$
||x||_2 = \sqrt{\sum_{i=1}^{n}x_i^2}
$$

In [26]:
# L2范数-向量元素平方和的平方根
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$$
||x||_1 = \sum_{i=1}^{n}|x_i|
$$

In [27]:
# L1范数-向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)